version: '3.8'

services:
  web:
    image: python:3.9
    container_name: sysmon_web
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && 
             uvicorn backend.server:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
  
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: sysmon_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  
  sysmon_notifier:
    image: python:3.9  
    container_name: sysmon_notifier
    working_dir: /app
    volumes:
      - .:/app  
    environment:
      - RECEIVER_EMAIL=${RECEIVER_EMAIL}  # Email from .env file or inline
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements.txt &&
      python3 run_notification_client.py
      "

  frontend:
    image: node:23.3.0-alpine3.19
    working_dir: /app      
    volumes:
      - ./frontend:/app    
    ports:
      - "4173:4173"        
    command: >
      sh -c "npm ci &&
             npm run build &&
             npm run preview"

  # db:
  #   image: mysql:8.0
  #   container_name: sysmon_db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpasswd
  #     MYSQL_DATABASE: settings
  #     MYSQL_USER: sysmon_user
  #     MYSQL_PASSWORD: sysmonpasswd
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"

volumes:
  sysmon_data:
  mysql_data:
